sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jonassingbo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jonassingbo/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker -react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-674998283905"
  bucket_path: "docker -react"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
